-- ng_loan_market：Flink Lookup id 点查索引（仅 MySQL 8.0.13+ 函数索引）
-- 当前 market 库为 5.7 时请依赖 Lookup 缓存（LOOKUP_CACHE_TTL=300s+），勿强跑本文件。
-- MySQL 8+: CREATE INDEX idx_user_id_signed ON `user` ((CAST(id AS SIGNED)));
